const CardsDB = {
  commanders: {
    Elyse: 'QYYBA',
    Tarian: '4!fAA',
    Aria: 'AIOBA',
    Yuriel: '4~IBA',
    Ursurio: 'YgdBA',
    Decim: 'IQTBA',
    Orgoth: 'gn5AA',
  },
  cards: {
    'Bluefire|5|Emp': 'amNCF',
    'Bluefire|6|Emp': 'C2NCF',
    'Bluefire|7|Emp': 'qFOCF',
    'Bluefire|8|Emp': 'SVOCF',
    'Bluefire|9|Emp': '6kOCF',
    'Bluefire|10|Emp': 'i0OCF',

    'Bluefire|5|Hp': 'dlNCF',
    'Bluefire|6|Hp': 'F1NCF',
    'Bluefire|7|Hp': 'tEOCF',
    'Bluefire|8|Hp': 'VUOCF',
    'Bluefire|9|Hp': '9jOCF',
    'Bluefire|10|Hp': 'lzOCF',

    'Korg|5|Hp': 'VgDEF',
    'Korg|6|Hp': '9vDEF',
    'Korg|7|Hp': 'l~DEF',
    'Korg|8|Hp': 'NPEEF',
    'Korg|9|Hp': '1eEEF',
    'Korg|10|Hp': 'duEEF',

    'Korg|5|Enr': 'PkDEF',
    'Korg|6|Enr': '3zDEF',
    'Korg|7|Enr': 'fDEEF',
    'Korg|8|Enr': 'HTEEF',
    'Korg|9|Enr': 'viEEF',
    'Korg|10|Enr': 'XyEEF',

    'Darkas|5|Hp': 't6kFF',
    'Darkas|6|Hp': 'VKlFF',
    'Darkas|7|Hp': '9ZlFF',
    'Darkas|8|Hp': 'lplFF',
    'Darkas|9|Hp': 'N5lFF',
    'Darkas|10|Hp': '1ImFF',

    'Darkas|5|Sco': 'a8kFF',
    'Darkas|6|Sco': 'CMlFF',
    'Darkas|7|Sco': 'qblFF',
    'Darkas|8|Sco': 'SrlFF',
    'Darkas|9|Sco': '66lFF',
    'Darkas|10|Sco': 'iKmFF',

    'Vern|7|Arm': 'XG6HF',
    'Vern|8|Arm': '~V6HF',
    'Vern|9|Arm': 'nl6HF',
    'Vern|10|Arm': 'P16HF',

    'Altos|5|Veng': 'V!iCH',
    'Altos|6|Veng': '9NjCH',
    'Altos|7|Veng': 'ldjCH',
    'Altos|8|Veng': 'NtjCH',
    'Altos|9|Veng': '18jCH',
    'Altos|10|Veng': 'dMkCH',

    'R3|4|Arm': '~zuSI',
    'R3|5|Arm': 'nDvSI',
    'R3|6|Arm': 'PTvSI',
    'R3|7|Arm': '3ivSI',
    'R3|8|Arm': 'fyvSI',
    'R3|9|Arm': 'HCwSI',
    'R3|10|Arm': 'vRwSI',

    'R3|4|Emp': 'J0uSI',
    'R3|5|Emp': 'xDvSI',
    'R3|6|Emp': 'ZTvSI',
    'R3|7|Emp': 'BjvSI',
    'R3|8|Emp': 'pyvSI',
    'R3|9|Emp': 'RCwSI',
    'R3|10|Emp': '5RwSI',

    'Atlas|Emp': '6ahhC',
    'Atlas|Hp': '9ZhhC',

    'Coldsteel|4|Hex': 'YiUjJ',
    'Coldsteel|5|Hex': 'AyUjJ',
    'Coldsteel|6|Hex': 'oBVjJ',
    'Coldsteel|7|Hex': 'QRVjJ',
    'Coldsteel|8|Hex': '4gVjJ',
    'Coldsteel|9|Hex': 'gwVjJ',
    'Coldsteel|10|Hex': 'IAWjJ',

    'Trafyr|4|Hp': 'V2ohJ',
    'Trafyr|5|Hp': '9FphJ',
    'Trafyr|6|Hp': 'lVphJ',
    'Trafyr|7|Hp': 'NlphJ',
    'Trafyr|8|Hp': '10phJ',
    'Trafyr|9|Hp': 'dEqhJ',
    'Trafyr|10|Hp': 'FUqhJ',

    'Trafyr|4|Hex': 'w3ohJ',
    'Trafyr|5|Hex': 'YHphJ',
    'Trafyr|6|Hex': 'AXphJ',
    'Trafyr|7|Hex': 'omphJ',
    'Trafyr|8|Hex': 'Q2phJ',
    'Trafyr|9|Hex': '4FqhJ',
    'Trafyr|10|Hex': 'gVqhJ',

    'Trafyr|4|Heal': '12ohJ',
    'Trafyr|5|Heal': 'dGphJ',
    'Trafyr|6|Heal': 'FWphJ',
    'Trafyr|7|Heal': 'tlphJ',
    'Trafyr|8|Heal': 'V1phJ',
    'Trafyr|9|Heal': '9EqhJ',
    'Trafyr|10|Heal': 'lUqhJ',

    'Sivun|5|War': 'OPYGF',
    'Sivun|6|War': '2eYGF',
    'Sivun|7|War': 'euYGF',
    'Sivun|8|War': 'G!YGF',
    'Sivun|9|War': 'uNZGF',
    'Sivun|10|War': 'WdZGF',

    'Sivun|5|Hp': '9LYGF',
    'Sivun|6|Hp': 'lbYGF',
    'Sivun|7|Hp': 'NrYGF',
    'Sivun|8|Hp': '16YGF',
    'Sivun|9|Hp': 'dKZGF',
    'Sivun|10|Hp': 'FaZGF',

    'Sivun|5|Hp10': 'oTYGF',
    'Sivun|6|Hp10': 'QjYGF',
    'Sivun|7|Hp10': '4yYGF',
    'Sivun|8|Hp10': 'gCZGF',
    'Sivun|9|Hp10': 'ISZGF',
    'Sivun|10|Hp10': 'whZGF',

    'Leroux|5|Val': 'AaVDF',
    'Leroux|6|Val': 'opVDF',
    'Leroux|7|Val': 'Q5VDF',
    'Leroux|8|Val': '4IWDF',
    'Leroux|9|Val': 'gYWDF',
    'Leroux|10|Val': 'IoWDF',

    'Leroux|5|Hp': 'NXVDF',
    'Leroux|6|Hp': '1mVDF',
    'Leroux|7|Hp': 'd2VDF',
    'Leroux|8|Hp': 'FGWDF',
    'Leroux|9|Hp': 'tVWDF',
    'Leroux|10|Hp': 'VlWDF',

    'Leroux|6|Sip': 'fpVDF',
    'Leroux|7|Sip': 'H5VDF',
    'Leroux|8|Sip': 'vIWDF',
    'Leroux|9|Sip': 'XYWDF',
    'Leroux|10|Sip': '~nWDF',

    'Lok|5|Hp': 'NTxAF',
    'Lok|6|Hp': '1ixAF',
    'Lok|7|Hp': 'dyxAF',
    'Lok|8|Hp': 'FCyAF',
    'Lok|9|Hp': 'tRyAF',
    'Lok|10|Hp': 'VhyAF',

    'Lok|6|Blt': 'akxAF',
    'Lok|7|Blt': 'C0xAF',
    'Lok|8|Blt': 'qDyAF',
    'Lok|9|Blt': 'STyAF',
    'Lok|10|Blt': '6iyAF',

    'Howa|4|Sco': '655DH',
    'Howa|5|Sco': 'iJ6DH',
    'Howa|6|Sco': 'KZ6DH',
    'Howa|7|Sco': 'yo6DH',
    'Howa|8|Sco': 'a46DH',
    'Howa|9|Sco': 'CI7DH',
    'Howa|10|Sco': 'qX7DH',

    'Howa|4|Hp': 'N45DH',
    'Howa|5|Hp': '1H6DH',
    'Howa|6|Hp': 'dX6DH',
    'Howa|7|Hp': 'Fn6DH',
    'Howa|8|Hp': 't26DH',
    'Howa|9|Hp': 'VG7DH',
    'Howa|10|Hp': '9V7DH',

    'Howa|4|Hp10': '5~5DH',
    'Howa|5|Hp10': 'hP6DH',
    'Howa|6|Hp10': 'Jf6DH',
    'Howa|7|Hp10': 'xu6DH',
    'Howa|8|Hp10': 'Z!6DH',
    'Howa|9|Hp10': 'BO7DH',
    'Howa|10|Hp10': 'pd7DH',

    'Aeron|4|Hex': 'o3nCH',
    'Aeron|5|Hex': 'QHoCH',
    'Aeron|6|Hex': '4WoCH',
    'Aeron|7|Hex': 'gmoCH',
    'Aeron|8|Hex': 'I2oCH',
    'Aeron|9|Hex': 'wFpCH',
    'Aeron|10|Hex': 'YVpCH',

    'Aeron|4|Hp': 'N2nCH',
    'Aeron|5|Hp': '1FoCH',
    'Aeron|6|Hp': 'dVoCH',
    'Aeron|7|Hp': 'FloCH',
    'Aeron|8|Hp': 't0oCH',
    'Aeron|9|Hp': 'VEpCH',
    'Aeron|10|Hp': '9TpCH',

    'Nuvis|7|Emp': 'h~aDF',
    'Nuvis|8|Emp': 'JPbDF',
    'Nuvis|9|Emp': 'xebDF',
    'Nuvis|10|Emp': 'ZubDF',

    'Sgt|6|War': '2qTEF',
    'Sgt|7|War': 'ObTEF',
    'Sgt|8|War': '2qTEF',
    'Sgt|9|War': 'e6TEF',
    'Sgt|10|War': 'GKUEF',

    'Sgt|6|Hp': 'VITEF',
    'Sgt|7|Hp': '9XTEF',
    'Sgt|8|Hp': 'lnTEF',
    'Sgt|9|Hp': 'N3TEF',
    'Sgt|10|Hp': '1GUEF',

    'Sgt|5|Val': 'g7SEF',
    'Sgt|6|Val': 'ILTEF',
    'Sgt|7|Val': 'waTEF',
    'Sgt|8|Val': 'YqTEF',
    'Sgt|9|Val': 'A6TEF',
    'Sgt|10|Val': 'oJUEF',

    'Spark|6|Veng': 'dr5FF',
    'Spark|7|Veng': 'F75FF',
    'Spark|8|Veng': 'tK6FF',
    'Spark|9|Veng': 'Va6FF',
    'Spark|10|Veng': '9p6FF',

    'Mechau|6|Blt': '6MOGF',
    'Mechau|7|Blt': 'icOGF',
    'Mechau|8|Blt': 'KsOGF',
    'Mechau|9|Blt': 'y7OGF',
    'Mechau|10|Blt': 'aLPGF',

    'Mechau|6|Leg': 'aMOGF',
    'Mechau|7|Leg': 'CcOGF',
    'Mechau|8|Leg': 'qrOGF',
    'Mechau|9|Leg': 'S7OGF',
    'Mechau|10|Leg': '6KPGF',

    'Predonyx|8|Emp': 'pxBFF',
    'Predonyx|9|Emp': 'RBCFF',
    'Predonyx|10|Emp': '5QCFF',

    'Mathay|7|Sco': 'K~0HF',
    'Mathay|8|Sco': 'yO1HF',
    'Mathay|9|Sco': 'ae1HF',
    'Mathay|10|Sco': 'Cu1HF',

    'Mathay|7|Poi': '8~0HF',
    'Mathay|8|Poi': 'kP1HF',
    'Mathay|9|Poi': 'Mf1HF',
    'Mathay|10|Poi': '0u1HF',

    'Remi|6|Hex': 'IobDH',
    'Remi|7|Hex': 'w3bDH',
    'Remi|8|Hex': 'YHcDH',
    'Remi|9|Hex': 'AXcDH',
    'Remi|10|Hex': 'omcDH',

    'Yanlong|7|Hp': '1TyGF',
    'Yanlong|8|Hp': 'djyGF',
    'Yanlong|9|Hp': 'FzyGF',
    'Yanlong|10|Hp': 'tCzGF',

    'Froggit|6|Sip': '~IBDF',
    'Froggit|7|Sip': 'nYBDF',
    'Froggit|8|Sip': 'PoBDF',
    'Froggit|9|Sip': '33BDF',
    'Froggit|10|Sip': 'fHCDF',

    'Froggit|6|Sco': 'CIBDF',
    'Froggit|7|Sco': 'qXBDF',
    'Froggit|8|Sco': 'SnBDF',
    'Froggit|9|Sco': '62BDF',
    'Froggit|10|Sco': 'iGCDF',

    'Coldsnap T|Hex': 'QY0qH',

    'Narix|Breath': 'jXXjC',
    'Narix|Hp': '1UXjC',

    'Grimkite|Sco': '6!B0H',

    'Coalheart|8|Enr': 'foYCF',
    'Coalheart|9|Enr': 'H4YCF',
    'Coalheart|10|Enr': 'vHZCF',

    'Rhynio|10|Sco': 'iDHBF',
    'Shadomeka|10|Wea': 'ipoEF',
    'Scylla|Hp': 'NxKmC',

    'B4|10|Arm': '3eAEH',
    'Dragon Family|10|Breath': 'TAsDH',

    'El Dora|Heal': 'FhSpG',
    'Verus|Hp': 'tTxnC',
    'Illu|10|Bar': 'aXeEF',
    'Shenami T E|Heal': 'F8o1I',

    'Sparky|7|Bar': 'KO8CF',
    'Sparky|8|Bar': 'yd8CF',
    'Sparky|9|Bar': 'at8CF',
    'Sparky|10|Bar': 'C98CF',

    'Ralgan|10|Emp': 'izlBF',
    'Chronomech M|Emp': 'C80JJ',

    'Lev|5|Poi': 'kNsAF',
    'Lev|6|Poi': 'MdsAF',
    'Lev|7|Poi': '0ssAF',
    'Lev|8|Poi': 'c8sAF',
    'Lev|9|Poi': 'EMtAF',
    'Lev|10|Poi': 'sbtAF',

    'TZ-530|8|Bar': 'K6yAH',

    'Gearchro|Veng': 'lbVoH',
    'Amrita|Heal': 't3NCJ',
    'Grimkite|Sco': '6!B0H',
    'Brightcore|Arm': 'y26hG',
    'Hallowed Drakon|Sco': 'y26hG',
    'Owlnaut|Heal': '9KPgG',
    'Roasterbots|Poi': 'c2W4H',
    'Zuphlas|Emp': 'SATCJ',
    'Aloier|Hp': 'V!ldG',
    'Aloier|Bar': 'q!ldG',
    'Aloier|Arm': 'H~ldG',

    'Cress|Blt': 'SRYrH',
    'Steelscale|Arm': 'PDHbG',
    'Mirrorwing|Veng': 'NcFmG',
    'Lustrous|Heal': '9gDkC',
    'Stormcleaver|Bar': 'arYTB',
    'Lumber|Arm': 'HE3EJ',
    'Forgewing|Fer': 'MoDCJ',

    'Steelwing|Arm': 'nAWtC',
    'Steelwing|Blt': 'ZBWtC',
    'Impenetrable|Arm': '3X~xC',
    'Impenetrable|Blt': 'qY~xC',
    'Impenetrable|Hp': 'FX~xC',
    'Herald of A|Veng': 'VltwC',

    'Kluum|10|Hp': 'NieGF',
    'K`luum|10|Hp': 'NieGF',
    'Luum|10|Hp': 'NieGF',

    'Loco|9|Hp': '9h8AF',
    'Loco|10|Hp': 'lx8AF',

    'Loco|9|Ber': 'pk8AF',
    'Loco|10|Ber': 'R08AF',

    'Gendra|9|Emp': 'aNuCH',
    'Gendra|10|Emp': 'CduCH',

    'Allies|7|Emp': 'Sz0FF',
    'Allies|8|Emp': '6C1FF',
    'Allies|9|Emp': 'iS1FF',
    'Allies|10|Emp': 'Ki1FF',

    'Aero|10|Hp': 'FT6BF',

    'Typhoeus|10|Ward': '!8BBF',

    'Armada|7|Blt': 'yr0SI',
    'Armada|8|Blt': 'a70SI',
    'Armada|9|Blt': 'CL1SI',
    'Armada|10|Blt': 'qa1SI',
  },
};
